packages:
  - priv-playground
  - priv-website

catalog:
  '@js-joda/core': ^3.2.0
  '@tailwindcss/vite': ^4.3.3
  '@types/node': ^25.9.3
  '@types/subset-font': ^2.3.0
  es-module-lexer: ^2.3.2
  subset-font: ^2.7.0
  tailwindcss: ^4.3.3
  typescript: ^6.0.3
  vite: ^8.0.16
  vitepress: ^2.0.0-alpha.18
  vue: ^3.5.40
  vue-tsc: ^3.3.11
