name: website

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/website.yml'

concurrency:
  group: cloudflare-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: website/package.json

      - uses: pnpm/action-setup@v6
        with:
          package_json_file: website/package.json

      - run: pnpm install

      - run: pnpm build

      - uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy website/.vitepress/dist --project-name=priv-kit
